matrix:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      dist: trusty
      language: python
      include:
        - python: 3.6
          dist: xenial
      install:
        - python --version
        - pip install -U pip
        - pip install coverage
        - pip install -r requirements.txt
        - python setup.py -q install
      script: travis_wait 35 coverage run -m unittest discover
sudo: false
cache: pip
after_success:
  - bash <(curl -s https://codecov.io/bash)